services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  device_server:
    image: clue/json-server
    restart: always
    ports:
      - 3000:80
    volumes:
      - ./services/database/db.json:/data/db.json
    command: ["--watch", "/data/db.json"]
  database:
    build: ./services/database
    command: sh -c "npm run migration:all && echo 'Migrations complete'"
    environment:
      DB_HOST: db
    depends_on:
      db:
        condition: service_started
